# Generated by Django 4.0.1 on 2022-01-13 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('git_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PullRequest',
            new_name='PullRequestModel',
        ),
    ]
