# Generated by Django 4.0.1 on 2022-01-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_backend', '0002_rename_pullrequest_pullrequestmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequestmodel',
            name='merge_commit_message',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
