# Generated by Django 4.0.1 on 2022-01-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_backend', '0003_pullrequestmodel_merge_commit_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequestmodel',
            name='pr_title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
