# Generated by Django 4.0.1 on 2022-01-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_backend', '0004_pullrequestmodel_pr_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequestmodel',
            name='base_branch_name',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='pullrequestmodel',
            name='compare_branch_name',
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
