# Generated by Django 4.0.1 on 2022-01-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_backend', '0007_alter_pullrequestmodel_base_branch_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequestmodel',
            name='base_branch_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pullrequestmodel',
            name='compare_branch_name',
            field=models.CharField(max_length=200),
        ),
    ]
